::tns::tions
::sns::ssions
::zns::sions
::isms::ismes
::ists::istes
::gms::grammes
::gfs::graphes
::gfis::graphies
::gfqs::graphiques
::lgis::logies
::lgqs::logiques
::tnrs::tionnaires
::snrs::sionnaires
::tnles::tionnelles
::snles::ssionnelles
::znles::sionnelles
::tnls::tionnels
::snls::ssionnels
::znls::sionnels
::isats::issants
::iqs::iques
::pns::phones
::tls::tiels
::tles::tielles
::pds::prendres
::abs::ables
::ibs::ibles
::fcs::ifications
::fts::ifications
::fcns::ifications
::ftns::ifications
::fvs::ificatives
::ffs::ificatifs
::tn::tion
::sn::ssion
::zn::sion
::ism::isme
::ist::iste
::gm::gramme
::gf::graphe
::gfi::graphie
::gfq::graphique
::lgi::logie
::lgq::logique
::tnr::tionnaire
::snr::sionnaire
::tnle::tionnelle
::snle::ssionnelle
::znle::sionnelle
::tnl::tionnel
::snl::ssionnel
::znl::sionnel
::isat::issant
::iq::ique
::pn::phone
::tl::tiel
::tle::tielle
::pd::prendre
::ab::able
::ib::ible
::fc::ification
::ft::ification
::fcn::ification
::ftn::ification
::fv::ificative
::ff::ificatif
::tt::tôt
::mt::ment
::vr::voir
::fr::faire
::ibm::iblement
::abm::ablement
::lm::lement
::bm::blement
::qm::quement
::tm::tement
::tlm::tiellement
::gfm::graphiquement
::gfqm::graphiquement
::gfim::graphiquement
::vm::ivement
::nm::nement
::dm::dement
::tnlm::tionnellement
::snlm::ssionnellement
::znlm::sionnellement
::test::yes, there has been test.
::notest::no, there has not been test.
